directories:
  output: instalador
  buildResources: build
appId: com.pdv.desktop
productName: PDV Desk
win:
  target: nsis
  icon: imagem/build/icon.ico
artifactName: PDV Desk Setup ${version}.exe
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: PDV Desk
  installerIcon: imagem/build/icon.ico
  installerSidebar: installerSidebar.bmp
files:
  - filter:
      - pdv-standalone.html
      - main.js
      - database.js
      - package.json
      - modelos cupom/**/*
electronVersion: 27.0.0
